# Generated by Django 4.2.1 on 2023-06-13 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='admin', max_length=30)),
                ('Password', models.CharField(default='admin', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssignmentNo', models.IntegerField()),
                ('Marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='null', max_length=30)),
                ('Pass', models.CharField(default='null', max_length=15)),
                ('Emp_no', models.CharField(max_length=15)),
                ('Faculty_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FacultySubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batches', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.batches')),
                ('Faculties', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.faculties')),
            ],
        ),
        migrations.CreateModel(
            name='pdfconvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_candidate', models.CharField(default='', max_length=300)),
                ('regno', models.CharField(default='', max_length=300)),
                ('clgname', models.CharField(default='', max_length=300)),
                ('branch', models.CharField(default='', max_length=300)),
                ('sem', models.CharField(default='', max_length=300)),
                ('pgm', models.CharField(default='', max_length=300)),
                ('coursname', models.CharField(default='', max_length=3000)),
                ('code', models.CharField(default='', max_length=300)),
                ('grade', models.CharField(default='', max_length=300)),
                ('credits', models.CharField(default='', max_length=300)),
                ('mnthyearofexam', models.CharField(default='', max_length=300)),
                ('totcrd', models.IntegerField(default='1')),
                ('sgpa', models.FloatField(default='1.0')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester_name', models.CharField(max_length=5)),
                ('Courses', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_code', models.CharField(max_length=6)),
                ('Subject_name', models.CharField(max_length=75)),
                ('Courses', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.courses')),
                ('Semester', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='null', max_length=30)),
                ('Pass', models.CharField(default='null', max_length=15)),
                ('KTUID', models.CharField(max_length=15)),
                ('Admnno', models.CharField(max_length=15)),
                ('Rollno', models.CharField(max_length=3)),
                ('Name', models.CharField(max_length=30)),
                ('Religion', models.CharField(max_length=15)),
                ('Category', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=12)),
                ('Dob', models.CharField(max_length=12)),
                ('Address', models.TextField()),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('Personalmail', models.EmailField(max_length=30)),
                ('RITmail', models.EmailField(max_length=30)),
                ('Nationality', models.CharField(max_length=20)),
                ('Aadharno', models.CharField(max_length=12)),
                ('Blood_group', models.CharField(max_length=15)),
                ('Year_of_admission', models.IntegerField(default=1)),
                ('Status', models.CharField(max_length=15)),
                ('Guardian_name', models.CharField(max_length=30)),
                ('Guardian_contact_no', models.CharField(max_length=10)),
                ('Batches', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.batches')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesExamMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeriesExamNo', models.IntegerField()),
                ('Marks', models.IntegerField()),
                ('Students', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.students')),
                ('Subjects', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Hour', models.IntegerField()),
                ('LeaveType', models.CharField(max_length=15)),
                ('Reason', models.TextField()),
                ('DL_upload', models.FileField(upload_to='pdf_files/')),
                ('Adv_approval', models.BooleanField(default=0)),
                ('Fac_approval', models.BooleanField(default=0)),
                ('Status', models.CharField(max_length=15)),
                ('Faculties', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.faculties')),
                ('Students', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.students')),
                ('Subjects', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='InternalMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendancemarks', models.IntegerField()),
                ('Total', models.IntegerField()),
                ('AssignmentMarks', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.assignmentmarks')),
                ('FacultySubjects', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.facultysubjects')),
                ('SeriesExamMarks', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.seriesexammarks')),
                ('Students', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.students')),
            ],
        ),
        migrations.CreateModel(
            name='GradeCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(max_length=5)),
                ('Subject_code', models.CharField(max_length=5)),
                ('Subject_name', models.TextField()),
                ('Credit', models.IntegerField()),
                ('Month_and_year', models.CharField(max_length=15)),
                ('Grade', models.CharField(max_length=5)),
                ('SGPA', models.FloatField()),
                ('Status', models.BooleanField(default=False)),
                ('Students', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.students')),
                ('Subjects', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.subjects')),
            ],
        ),
        migrations.AddField(
            model_name='facultysubjects',
            name='Subjects',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.subjects'),
        ),
        migrations.CreateModel(
            name='Electives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subjects', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Electives', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.electives')),
                ('Students', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.students')),
            ],
        ),
        migrations.AddField(
            model_name='batches',
            name='Courses',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.courses'),
        ),
        migrations.AddField(
            model_name='batches',
            name='Semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.semester'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Hour', models.IntegerField()),
                ('Status', models.CharField(default='P', max_length=7)),
                ('Batches', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.batches')),
                ('Faculties', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.faculties')),
                ('Students', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.students')),
                ('Subjects', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.subjects')),
            ],
        ),
        migrations.AddField(
            model_name='assignmentmarks',
            name='Students',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.students'),
        ),
        migrations.AddField(
            model_name='assignmentmarks',
            name='Subjects',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.subjects'),
        ),
        migrations.CreateModel(
            name='Advisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batches', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.batches')),
                ('Faculties', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.faculties')),
            ],
        ),
    ]
