# Generated by Django 4.2.1 on 2023-06-02 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Students',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.students'),
        ),
    ]
