# Generated by Django 4.2.1 on 2023-06-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_alter_attendance_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequests',
            name='Adv_approval',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='leaverequests',
            name='Fac_approval',
            field=models.BooleanField(default=None),
        ),
    ]
