# Generated by Django 4.2.1 on 2023-06-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_alter_leaverequests_adv_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequests',
            name='Adv_approval',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='leaverequests',
            name='Fac_approval',
            field=models.BooleanField(default=0),
        ),
    ]
