# Generated by Django 4.2.1 on 2023-06-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0004_alter_leaverequests_adv_approval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdfconvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_candidate', models.CharField(default='', max_length=300)),
                ('regno', models.CharField(default='', max_length=300)),
                ('clgname', models.CharField(default='', max_length=300)),
                ('branch', models.CharField(default='', max_length=300)),
                ('sem', models.CharField(default='', max_length=300)),
                ('pgm', models.CharField(default='', max_length=300)),
                ('coursname', models.CharField(default='', max_length=300)),
                ('code', models.CharField(default='', max_length=300)),
                ('grade', models.CharField(default='', max_length=300)),
                ('credits', models.CharField(default='', max_length=300)),
                ('mnthyearofexam', models.CharField(default='', max_length=300)),
                ('totcrd', models.IntegerField(default='1')),
                ('sgpa', models.FloatField(default='1.0')),
            ],
        ),
    ]
