# Generated by Django 4.2.1 on 2023-06-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0005_pdfconvert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequests',
            name='DL_upload',
            field=models.FileField(upload_to='pdf_files/'),
        ),
    ]
