# Generated by Django 4.2.1 on 2023-06-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0006_alter_leaverequests_dl_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfconvert',
            name='coursname',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
