# Generated by Django 4.2.2 on 2023-06-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0007_alter_pdfconvert_coursname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentmarks',
            name='Marks',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='seriesexammarks',
            name='Marks',
            field=models.FloatField(),
        ),
    ]
